version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # expose for Dokploy’s internal routing
    expose:
      - "80"
    # no volume needed, content is baked into the image
